apiVersion: apps/v1
kind: Deployment
metadata:
  name: firewall-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: firewall-app
  template:
    metadata:
      labels:
        app: firewall-app
    spec:
      containers:
      - name: app
        image: ashhwiithac22/firewall-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
